AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "expenseId"
          AttributeType: S
        - AttributeName: "expanseDate"
          AttributeType: S
      KeySchema:
        - AttributeName: "expenseId"
          KeyType: HASH
        - AttributeName: "expanseDate"
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: True

  EnterReceipt:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: src/enter-receipt
      Handler: index.handler
      Environment:
        Variables:
          EXPENSE_TABLE_NAME: !Ref DynamoDBTable
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt "DynamoDBTable.Arn"
      Events:
        APICREATE:
          Type: Api
          Properties:
            Path: /expense
            Method: POST

  ListExpenses:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: src/list-expenses
      Handler: index.handler
      Events:
        APILIST:
          Type: Api
          Properties:
            Path: /expenses
            Method: GET

  UpdateExpense:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: src/update-expense
      Handler: index.handler
      Events:
        APIUPDATE:
          Type: Api
          Properties:
            Path: /expense/{id}
            Method: PUT
